# -*- coding: utf-8 -*-
"""Image_Cartoon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VbLSV5pE_GssiHjsb8OfoKWGXIQtRX6U
"""

from google.colab import drive
drive.mount('/content/drive')

import cv2 #for image processing
#import easygui #to open the filebox
import numpy as np #to store image
import imageio #to read image stored at particular path

import sys
import matplotlib.pyplot as plt
import os
import tkinter as tk
from tkinter import filedialog
from tkinter import *
from PIL import ImageTk, Image

img = cv2.imread('/content/drive/My Drive/IMG_20180611_233312_264.jpg')
image2 = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.imshow(image2)

gray_image = cv2.cvtColor(image2, cv2.COLOR_BGR2GRAY)

plt.imshow(gray_image,cmap='gray')

smooth_gray = cv2.medianBlur(gray_image,5) #have to be odd number 
plt.imshow(smooth_gray,cmap='gray')

get_Edge = cv2.adaptiveThreshold(smooth_gray, 255, 
  cv2.ADAPTIVE_THRESH_MEAN_C, 
  cv2.THRESH_BINARY, 11,2)
plt.imshow(get_Edge,cmap='gray')

color_image = cv2.bilateralFilter(image2, 9, 300, 300)
plt.imshow(color_image,cmap='gray')

cartoon_image = cv2.bitwise_and(color_image, color_image, mask=get_Edge)
plt.imshow(cartoon_image,cmap='gray')